
package com.osi.re.ws.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serverPortType", targetNamespace = "urn:server")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns server.CreateRequestResponseType
     */
    @WebMethod(operationName = "CreateRequest", action = "urn:server#CreateRequest")
    @WebResult(name = "CreateRequestResponse", partName = "parameters")
    public CreateRequestResponseType createRequest(
        @WebParam(name = "CreateRequest", partName = "parameters")
        CreateRequestRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns server.CreateIncidentResponseType
     */
    @WebMethod(operationName = "CreateIncident", action = "urn:server#CreateIncident")
    @WebResult(name = "CreateIncidentResponse", partName = "parameters")
    public CreateIncidentResponseType createIncident(
        @WebParam(name = "CreateIncident", partName = "parameters")
        CreateIncidentRequestType parameters);

}
