
package com.osi.re.ws.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.osi.re.common.CommonUtilities;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
 //http://helpdesk.osius.com/RequestServer/SelectWebServiceCall?wsdl
//http://54.183.65.141/soc/RequestServer/SelectWebServiceCall?wsdl
//http://192.168.174.153/occ/RequestServer/SelectWebServiceCall?wsdl
//http://192.168.174.153/occ_v2/RequestServer/SelectWebServiceCall?wsdl
//http://54.183.65.141/soc_v2/RequestServer/SelectWebServiceCall?wsdl


//http://192.168.176.154/occ_v2/RequestServer/SelectWebServiceCall?wsdl prodPortalUrl
//http://isecure.igate.com/RequestServer/SelectWebServiceCall?wsdl   iGatePortalUrl

@WebServiceClient(name = "server", targetNamespace = "urn:server", wsdlLocation = "")
public class Server
    extends Service
{

    private final static URL SERVER_WSDL_LOCATION;
    private final static WebServiceException SERVER_EXCEPTION;
    private final static QName SERVER_QNAME = new QName("urn:server", "server");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	String wsdlUrl =CommonUtilities.getProperty("wsdl_url");
            url = new URL(wsdlUrl);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVER_WSDL_LOCATION = url;
        SERVER_EXCEPTION = e;
    }

    public Server() {
        super(__getWsdlLocation(), SERVER_QNAME);
    }

    public Server(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVER_QNAME, features);
    }

    public Server(URL wsdlLocation) {
        super(wsdlLocation, SERVER_QNAME);
    }

    public Server(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVER_QNAME, features);
    }

    public Server(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Server(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServerPortType
     */
    @WebEndpoint(name = "serverPort")
    public ServerPortType getServerPort() {
        return super.getPort(new QName("urn:server", "serverPort"), ServerPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerPortType
     */
    @WebEndpoint(name = "serverPort")
    public ServerPortType getServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:server", "serverPort"), ServerPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVER_EXCEPTION!= null) {
            throw SERVER_EXCEPTION;
        }
        return SERVER_WSDL_LOCATION;
    }

}
