
package com.osi.agent.webservicestub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CheckConnectionIntf", targetNamespace = "http://webservice.agent.osius.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CheckConnectionIntf {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "executeSnmpTable", targetNamespace = "http://webservice.agent.osius.com/", className = "com.osi.agent.webservicestub.ExecuteSnmpTable")
    @ResponseWrapper(localName = "executeSnmpTableResponse", targetNamespace = "http://webservice.agent.osius.com/", className = "com.osi.agent.webservicestub.ExecuteSnmpTableResponse")
    @Action(input = "http://webservice.agent.osius.com/CheckConnectionIntf/executeSnmpTableRequest", output = "http://webservice.agent.osius.com/CheckConnectionIntf/executeSnmpTableResponse")
    public String executeSnmpTable(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
